#!/bin/bash


echo "gettiong app"
wget http://192.168.1.175:8081/app1.zip

echo "unzipping app"
unzip app1.zip

echo "copying app"
cp app1/index.js app1/index.bak

echo "populating app"
echo "const express = require(\"express\");
const axios = require('axios');

const app = express();

app.get('/', async (req, res) => {
    try {
        const { data } = await axios.get('http://10.0.0.10:80')
        res.send([...data, 'app1 status: OK'])

    } catch (error) {
        console.log(error.message)
        res.send(['app1 status: NOT OK'])
    }
})

app.listen(80)" > app1/index.js

# systemctl disable firewalld
# ifdown ens160 && ifup ens160
# nmcli reload
npm install pm2 -g
systemctl start firewalld

firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --reload

# npm install -g forever

#nohup node app1/index.js > /dev/null 2>&1 & disown

#sh 2021-linux-scripting/app1Run.sh
pm2 start app1/index.js