#!/bin/bash



echo "gettiong app"
wget http://10.0.0.2:8081/app1.zip

echo "unzipping app"
unzip app1.zip

echo "copying app"
cp app1/index.js app1/index.bak
mv app1 app3
echo "populating app"
echo "const express = require(\"express\");
const axios = require('axios');

const app = express();

app.get('/', async (req, res) => {
    try {
        const { data } = await axios.get('http://app4:80')
        res.send([...data, 'app3 status: OK'])

    } catch (error) {
        console.log(error.message)
        res.send(['app3 status: NOT OK'])
    }
})

app.listen(80)" > app3/index.js

systemctl start firewalld

firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --reload
# npm install -g forever

node app3/index.js &