#!/bin/bash

dnf makecache

dnf install dhcp-server -y

mv /etc/sysconfig/network-scripts/ifcfg-ens160 /etc/sysconfig/network-scripts/ifcfg-ens160.bak

echo "TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
NAME=ens160
UUID=32d7c5eb-362e-4764-8ddd-847ab5c94e8e
DEVICE=ens160
ONBOOT=yes
PREFIX=8
IPADDR=10.0.0.2
GATEWAY=10.0.0.1
DNS1=10.0.0.3
DOMAIN=\"easlab.local\"" > /etc/sysconfig/network-scripts/ifcfg-ens160

mv /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.init

echo "
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp-server/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#

default-lease-time 600000;
max-lease-time 720000;

ddns-update-style none;
authoritative;

subnet 10.0.0.0 netmask 255.255.255.0 {
	range 10.0.0.10 10.0.0.50;
	option routers 10.0.0.1;
	option subnet-mask 255.255.255.0;
	option domain-name \"easlab.local\";
	option domain-search \"easlab.local\";
	option domain-name-servers 10.0.0.3, 8.8.8.8, 8.8.4.4;
}

host DNS {
	hardware ethernet 00:50:56:af:be:44;
	fixed-address 10.0.0.3;
}

host Gateway {
	hardware ethernet 00:50:56:af:82:90;
	fixed-address 10.0.0.1;
}" > /etc/dhcp/dhcpd.conf

firewall-cmd --add-service=dhcp --permanent

firewall-cmd --reload

ifup ens160

nmcli connection reload

systemctl start dhcpd