#!/bin/bash				

echo "IPADDR=10.0.0.1" >> /etc/sysconfig/network-script/ifcfg-ens160

dnf makecache

dnf install dhcp-server

mv /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.bak

echo "default-lease-time 600; 
max-lease-time 7200; 
ddns-update-style none;
authoritative;

subnet 10.0.0.0 net mask 255.255.255.0 {
range 10.0.0.10 10.0.0.50;				
option routers 10.0.0.1;						
option subnet-mask 255.255.255.0;			
option domain-name-servers 10.0.0.3;	
}" >> /etc/dhcp/dhcp.conf

ifdown ens160 && ifup ens160

systemctl start dhcpd

firewall-cmd --add-service=dhcp --permanent

firewall-cmd --reload

systemctl restart dhcpd
